WebApplication3/Models/user.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace WebApplication3.Models
{
    public class user
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id_user { get; set; }

        public string user_name { get; set; }
        public string mail { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int? rol_id { get; set; }

        public rol rol { get; set; }
        public ICollection<bron> bron { get; set; }
        public ICollection<izbr> izbr { get; set; }
    }
}

WebApplication3/Controllers/MarksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class MarksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MarksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Marks
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var marks = from m in _context.Marks
                        select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                marks = marks.Where(m => m.name_marka.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    marks = marks.OrderByDescending(m => m.name_marka);
                    break;
                default:
                    marks = marks.OrderBy(m => m.name_marka);
                    break;
            }

            return View(await marks.AsNoTracking().ToListAsync());
        }

        // GET: Marks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marks = await _context.Marks
                .FirstOrDefaultAsync(m => m.id == id);
            if (marks == null)
            {
                return NotFound();
            }

            return View(marks);
        }

        // GET: Marks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Marks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name_marka")] Marks marks)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(marks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(marks);
        }

        // GET: Marks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marks = await _context.Marks.FindAsync(id);
            if (marks == null)
            {
                return NotFound();
            }
            return View(marks);
        }

        // POST: Marks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name_marka")] Marks marks)
        {
            if (id != marks.id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(marks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarksExists(marks.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(marks);
        }

        // GET: Marks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marks = await _context.Marks
                .FirstOrDefaultAsync(m => m.id == id);
            if (marks == null)
            {
                return NotFound();
            }

            return View(marks);
        }

        // POST: Marks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var marks = await _context.Marks.FindAsync(id);
            if (marks != null)
            {
                _context.Marks.Remove(marks);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MarksExists(int id)
        {
            return _context.Marks.Any(e => e.id == id);
        }
    }
}

WebApplication3/Controllers/complsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class complsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public complsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: compls
        public async Task<IActionResult> Index()
        {
            return View(await _context.compl.ToListAsync());
        }

        // GET: compls/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compl = await _context.compl
                .FirstOrDefaultAsync(m => m.id == id);
            if (compl == null)
            {
                return NotFound();
            }

            return View(compl);
        }

        // GET: compls/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: compls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,kompl_name")] compl compl)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(compl);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(compl);
        }

        // GET: compls/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compl = await _context.compl.FindAsync(id);
            if (compl == null)
            {
                return NotFound();
            }
            return View(compl);
        }

        // POST: compls/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,kompl_name")] compl compl)
        {
            if (id != compl.id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(compl);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!complExists(compl.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compl);
        }

        // GET: compls/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compl = await _context.compl
                .FirstOrDefaultAsync(m => m.id == id);
            if (compl == null)
            {
                return NotFound();
            }

            return View(compl);
        }

        // POST: compls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var compl = await _context.compl.FindAsync(id);
            if (compl != null)
            {
                _context.compl.Remove(compl);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool complExists(int id)
        {
            return _context.compl.Any(e => e.id == id);
        }
    }
}

WebApplication3/Controllers/rolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class rolsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public rolsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: rols
        public async Task<IActionResult> Index()
        {
            return View(await _context.rol.ToListAsync());
        }

        // GET: rols/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rol = await _context.rol
                .FirstOrDefaultAsync(m => m.id == id);
            if (rol == null)
            {
                return NotFound();
            }

            return View(rol);
        }

        // GET: rols/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: rols/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,rol_name")] rol rol)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rol);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rol);
        }

        // GET: rols/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rol = await _context.rol.FindAsync(id);
            if (rol == null)
            {
                return NotFound();
            }
            return View(rol);
        }

        // POST: rols/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,rol_name")] rol rol)
        {
            if (id != rol.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rol);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!rolExists(rol.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rol);
        }

        // GET: rols/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rol = await _context.rol
                .FirstOrDefaultAsync(m => m.id == id);
            if (rol == null)
            {
                return NotFound();
            }

            return View(rol);
        }

        // POST: rols/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rol = await _context.rol.FindAsync(id);
            if (rol != null)
            {
                _context.rol.Remove(rol);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool rolExists(int id)
        {
            return _context.rol.Any(e => e.id == id);
        }
    }
}

WebApplication3/Views/users/AdminDashboard.cshtml
@{
    ViewData["Title"] = "Панель администратора";
}

<div class="container mt-5">
    <div class="row mb-4">
        <div class="col-12">
            <div class="card shadow-sm">
                <div class="card-header bg-danger text-white">
                    <h4><i class="fas fa-tachometer-alt me-2"></i>Панель управления</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <!-- Блок пользователей -->
                        <div class="col-md-4 mb-3">
                            <div class="card bg-light">
                                <div class="card-body text-center">
                                    <i class="fas fa-users fa-3x text-danger mb-3"></i>
                                    <h5>Пользователи</h5>
                                    <a asp-controller="Users" asp-action="Index" class="btn btn-sm btn-outline-danger">
                                        Управление <i class="fas fa-arrow-right ms-1"></i>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <!-- Блок автомобилей -->
                        <div class="col-md-4 mb-3">
                            <div class="card bg-light">
                                <div class="card-body text-center">
                                    <i class="fas fa-car fa-3x text-danger mb-3"></i>
                                    <h5>Автомобили</h5>
                                    <a asp-controller="Carsses" asp-action="Index" class="btn btn-sm btn-outline-danger">
                                        Управление <i class="fas fa-arrow-right ms-1"></i>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <!-- Блок справочников -->
                        <div class="col-md-4 mb-3">
                            <div class="card bg-light">
                                <div class="card-body text-center">
                                    <i class="fas fa-book fa-3x text-danger mb-3"></i>
                                    <h5>Справочники</h5>
                                    <div class="btn-group mt-2">
                                        <button class="btn btn-sm btn-outline-danger dropdown-toggle" type="button" data-bs-toggle="dropdown">
                                            Выбрать справочник
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="stranas" asp-action="Index"><i class="fas fa-globe me-2"></i>Страны</a></li>
                                            <li><a class="dropdown-item" asp-controller="salonches" asp-action="Index"><i class="fas fa-store me-2"></i>Салоны</a></li>
                                            <li><a class="dropdown-item" asp-controller="rols" asp-action="Index"><i class="fas fa-user-tag me-2"></i>Роли</a></li>
                                            <li><a class="dropdown-item" asp-controller="Marks" asp-action="Index"><i class="fas fa-car me-2"></i>Марки</a></li>
                                            <li><a class="dropdown-item" asp-controller="cvetas" asp-action="Index"><i class="fas fa-palette me-2"></i>Цвета</a></li>
                                            <li><a class="dropdown-item" asp-controller="compls" asp-action="Index"><i class="fas fa-cogs me-2"></i>Комплектации</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- Последние действия -->
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-header bg-danger text-white">
                    <h4><i class="fas fa-exclamation-circle me-2"></i>Последние действия</h4>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Новый пользователь зарегистрирован
                            <span class="badge bg-primary rounded-pill">только что</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Добавлен новый автомобиль
                            <span class="badge bg-primary rounded-pill">5 мин назад</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Обновлен справочник стран
                            <span class="badge bg-primary rounded-pill">10 мин назад</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Быстрая статистика -->
      
    </div>
</div>

WebApplication3/Views/users/Create.cshtml
@model WebApplication3.Models.user

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>user</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="user_name" class="control-label"></label>
                <input asp-for="user_name" class="form-control" />
                <span asp-validation-for="user_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mail" class="control-label"></label>
                <input asp-for="mail" class="form-control" />
                <span asp-validation-for="mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="login" class="control-label"></label>
                <input asp-for="login" class="form-control" />
                <span asp-validation-for="login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rol_id" class="control-label"></label>
                <select asp-for="rol_id" class ="form-control" asp-items="ViewBag.rol_id"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication3/Views/users/Edit.cshtml
@model WebApplication3.Models.user

@{
    ViewData["Title"] = "Редактирование пользователя";
}

<div class="container mt-4">
    <div class="card shadow">
        <div class="card-header bg-primary text-white">
            <h2><i class="fas fa-user-edit"></i> @ViewData["Title"]</h2>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="id_user" />

                        <div class="form-group mb-3">
                            <label asp-for="user_name" class="form-label fw-bold"></label>
                            <input asp-for="user_name" class="form-control" />
                            <span asp-validation-for="user_name" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="mail" class="form-label fw-bold"></label>
                            <input asp-for="mail" class="form-control" />
                            <span asp-validation-for="mail" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="login" class="form-label fw-bold"></label>
                            <input asp-for="login" class="form-control" />
                            <span asp-validation-for="login" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="password" class="form-label fw-bold"></label>
                            <input asp-for="password" class="form-control" type="password" />
                            <span asp-validation-for="password" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="rol_id" class="form-label fw-bold"></label>
                            <select asp-for="rol_id" class="form-control" asp-items="ViewBag.rol_id">
                                <option value="">-- Выберите роль --</option>
                            </select>
                            <span asp-validation-for="rol_id" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">
                                <i class="fas fa-save"></i> Сохранить
                            </button>
                            <a asp-action="Index" class="btn btn-secondary">
                                <i class="fas fa-arrow-left"></i> Назад к списку
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebApplication3/Views/users/Index.cshtml
@model IEnumerable<WebApplication3.Models.user>

@{
    ViewData["Title"] = "Управление пользователями";
}

<div class="container mt-4">
    <div class="card shadow">
        <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
            <h2><i class="fas fa-users"></i> @ViewData["Title"]</h2>
            <a asp-action="Create" class="btn btn-light">
                <i class="fas fa-user-plus"></i> Добавить пользователя
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead class="table-dark">
                        <tr>
                            <th>ID</th>
                            <th>Имя пользователя</th>
                            <th>Email</th>
                            <th>ID роли</th>
                            <th>Пароль</th>
                            <th class="text-end">Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.id_user)</td>
                                <td>@Html.DisplayFor(modelItem => item.user_name)</td>
                                <td>@Html.DisplayFor(modelItem => item.mail)</td>
                                <td>@Html.DisplayFor(modelItem => item.rol_id)</td>
                                <td>
                                    <div class="password-field">
                                        <span class="password-dots">•••••••</span>
                                        <span class="password-text d-none">@item.password</span>
                                        
                                    </div>
                                </td>
                                <td class="text-end">
                                    <div class="btn-group" role="group">
                                        <a asp-action="Details" asp-route-id="@item.id_user"
                                           class="btn btn-info btn-sm" title="Просмотр">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a asp-action="Edit" asp-route-id="@item.id_user"
                                           class="btn btn-warning btn-sm" title="Редактировать">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a asp-action="Delete" asp-route-id="@item.id_user"
                                           class="btn btn-danger btn-sm" title="Удалить">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer text-muted">
            Всего пользователей: @Model.Count()
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <style>
        .btn-group .btn {
            margin-right: 5px;
            border-radius: 4px;
            transition: all 0.3s;
        }

            .btn-group .btn:last-child {
                margin-right: 0;
            }

            .btn-group .btn:hover {
                transform: translateY(-2px);
                box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            }

        .table th {
            white-space: nowrap;
        }

        .card-header {
            border-radius: 0.25rem 0.25rem 0 0 !important;
        }

        .password-field {
            display: flex;
            align-items: center;
            gap: 5px;
        }

        .toggle-password {
            padding: 0.15rem 0.3rem;
            font-size: 0.8rem;
        }
    </style>
}

@section Scripts {
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function () {
            // Инициализация DataTable
            $('.table').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.11.5/i18n/ru.json'
                },
                responsive: true,
                columnDefs: [
                    { orderable: false, targets: [5] } // Отключаем сортировку для колонки с действиями
                ]
            });

            // Обработчик для кнопки показа/скрытия пароля
            $('.toggle-password').click(function () {
                var field = $(this).closest('.password-field');
                var dots = field.find('.password-dots');
                var text = field.find('.password-text');

                if (dots.hasClass('d-none')) {
                    dots.removeClass('d-none');
                    text.addClass('d-none');
                    $(this).html('<i class="fas fa-eye"></i>');
                } else {
                    dots.addClass('d-none');
                    text.removeClass('d-none');
                    $(this).html('<i class="fas fa-eye-slash"></i>');
                }
            });
        });
    </script>
}